### ISSUE TITLE
mistake

### ISSUE THREAD

**Issue by junxiesky** [DaRealAqua/ItemDisplay#6]
12:00:47 <Server thread/Critical> Error: "Call to undefined method pocketmine\event\entity\ItemSpawnEvent::getPlayer()" (EXCEPTION) in "plugins/ItemDisplay.phar/src/ItemText/Main" at line 49                                                  12:00:47 <Server thread/Debug> #0 src/pocketmine/plugin/MethodEventExecutor(42): ItemText\Main->onThrow(object pocketmine\event\entity\ItemSpawnEvent)
12:00:47 <Server thread/Debug> #1 src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object ItemText\Main, object pocketmine\event\entity\ItemSpawnEvent)                                             12:00:47 <Server thread/Debug> #2 src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\entity\ItemSpawnEvent)
12:00:47 <Server thread/Debug> #3 src/pocketmine/entity/object/ItemEntity(84): pocketmine\event\Event->call()           12:00:47 <Server thread/Debug> #4 src/pocketmine/entity/Entity(730): pocketmine\entity\object\ItemEntity->initEntity()
12:00:47 <Server thread/Debug> #5 src/pocketmine/entity/Entity(440): pocketmine\entity\Entity->__construct(object pocketmine\level\Level, object pocketmine\nbt\tag\CompoundTag)
12:00:47 <Server thread/Debug> #6 src/pocketmine/level/Level(1816): pocketmine\entity\Entity::createEntity(string[4] Item, object pocketmine\level\Level, object pocketmine\nbt\tag\CompoundTag)
12:00:47 <Server thread/Debug> #7 src/pocketmine/Player(3102): pocketmine\level\Level->dropItem(object pocketmine\math\Vector3, object pocketmine\item\ItemBlock, object pocketmine\math\Vector3, integer 40)
12:00:47 <Server thread/Debug> #8 src/pocketmine/inventory/transaction/action/DropItemAction(58): pocketmine\Player->dropItem(object pocketmine\item\ItemBlock)
12:00:47 <Server thread/Debug> #9 src/pocketmine/inventory/transaction/InventoryTransaction(311): pocketmine\inventory\transaction\action\DropItemAction->execute(object pocketmine\Player)
12:00:47 <Server thread/Debug> #10 src/pocketmine/Player(2462): pocketmine\inventory\transaction\InventoryTransaction->execute()
12:00:47 <Server thread/Debug> #11 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(160): pocketmine\Player->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
12:00:47 <Server thread/Debug> #12 src/pocketmine/network/mcpe/protocol/InventoryTransactionPacket(159): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
12:00:47 <Server thread/Debug> #13 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(120): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
12:00:47 <Server thread/Debug> #14 src/pocketmine/network/mcpe/protocol/BatchPacket(131): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket)
12:00:47 <Server thread/Debug> #15 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(120): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
12:00:47 <Server thread/Debug> #16 src/pocketmine/Player(3338): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
12:00:47 <Server thread/Debug> #17 src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
12:00:47 <Server thread/Debug> #18 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[18] 125.77.59.52 29132, object raklib\protocol\EncapsulatedPacket, integer 0)
12:00:47 <Server thread/Debug> #19 src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
12:00:47 <Server thread/Debug> #20 src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
12:00:47 <Server thread/Debug> #21 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
12:00:47 <Server thread/Debug> #22 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
12:00:47 <Server thread/Debug> #23 src/pocketmine/Server(2252): pocketmine\snooze\SleeperHandler->sleepUntil(double 1583236847.2706)
12:00:47 <Server thread/Debug> #24 src/pocketmine/Server(2099): pocketmine\Server->tickProcessor()
12:00:47 <Server thread/Debug> #25 src/pocketmine/Server(1686): pocketmine\Server->start()
12:00:47 <Server thread/Debug> #26 src/pocketmine/PocketMine(273): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[9] /root/pm/, string[17] /root/pm/plugins/)
12:00:47 <Server thread/Debug> #27 src/pocketmine/PocketMine(296): pocketmine\server()
12:00:47 <Server thread/Debug> #28 (11): require(string[64] phar:///root/pm/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by DaRealAqua** [comment]
Have you been to something? I have now done something I hope will work, you will not edit anything unless you know what I did

**Comment by junxiesky** [comment]
> Have you been to something? I have now done something I hope will work, you will not edit anything unless you know what I did

I run in Altay croe
After I entered the server, I threw out an item and got this error.

**Comment by DaRealAqua** [comment]
This is for pocketmine not altay!!!

**Comment by junxiesky** [comment]
> This is for pocketmine not altay!!!

Altay is a branch of pocketmine.
